// src/app/components/sidebar/sidebar.component.tsx
'use client';

import React, { useState } from 'react';
import { OverviewIcon } from './icons/overview-icon';
import { ServicesIcon } from './icons/services-icon';
import { JobsIcon } from './icons/jobs-icon';

export type View = 'general' | 'models' | 'services';

interface NavItem {
  id: View;
  icon: React.ReactNode;
  label: string;
}

const navItems: NavItem[] = [
  { id: 'general', icon: <OverviewIcon />, label: 'General' },
  { id: 'models', icon: <ServicesIcon />, label: 'Models' },
  { id: 'services', icon: <JobsIcon />, label: 'Services' },
];

interface SidebarProps {
  activeView: View;
  onViewChange: (view: View) => void;
  isCollapsed: boolean;
  onToggleCollapse: () => void;
}

const Sidebar = ({ activeView, onViewChange, isCollapsed, onToggleCollapse }: SidebarProps) => {
  return (
    <aside className={`flex flex-col bg-white border-r border-gray-200 transition-all duration-300 ${isCollapsed ? 'w-16' : 'w-64'}`}>
      <div className="flex items-center h-12 px-4 border-b border-gray-200">
        <button onClick={onToggleCollapse} className="p-1 rounded-full hover:bg-gray-100">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </button>
      </div>
      <nav className="flex-1 p-2 space-y-1">
        {navItems.map((item) => (
          <a
            key={item.id}
            href="#"
            onClick={(e) => {
              e.preventDefault();
              onViewChange(item.id);
            }}
            className={`flex items-center h-10 px-3 rounded-md text-gray-600 hover:bg-gray-100 ${activeView === item.id ? 'bg-blue-100 text-blue-600' : ''}`}
          >
            <div className="w-6 h-6">{item.icon}</div>
            {!isCollapsed && <span className="ml-3 text-sm font-medium">{item.label}</span>}
          </a>
        ))}
      </nav>
      <div className="p-2 border-t border-gray-200">
        <a href="#" className="flex items-center h-10 px-3 rounded-md text-gray-600 hover:bg-gray-100">
          <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
          {!isCollapsed && <span className="ml-3 text-sm font-medium">Release notes</span>}
        </a>
      </div>
    </aside>
  );
};

export default Sidebar;

// cloud-run/src/components/sidebar/sidebar.component.ts
import { ChangeDetectionStrategy, Component, input, output, signal, inject } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

export type View = 'overview' | 'services' | 'jobs' | 'worker-pools' | 'domain-mappings';

interface NavItem {
  id: View;
  icon: SafeHtml;
  label: string;
}

interface RawNavItem {
  id: View;
  icon: string;
  label: string;
}


@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SidebarComponent {
  activeView = input.required<View>();
  isCollapsed = input<boolean>(false);
  viewChange = output<View>();
  releaseNotesClicked = output<void>();
  toggleCollapse = output<void>();

  // Fix: Explicitly set the type for `sanitizer` to `DomSanitizer`. The type was being inferred as `unknown`.
  private sanitizer: DomSanitizer = inject(DomSanitizer);

  navItems = signal<NavItem[]>([]);

  constructor() {
    const rawNavItems: RawNavItem[] = [
      { id: 'overview', icon: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8h5z"/></svg>`, label: 'Overview' },
      { id: 'services', icon: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M13 22h8v-7h-3v-4h-2v4h-3v7M11 2h-8v7h3v4h2V9h3V2m-5 3h2v2H6V5m10 12h2v2h-2v-2M8 17v-2H6v2h2m-2-7V8H4v2h2Z"/></svg>`, label: 'Services' },
      { id: 'jobs', icon: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zm0-8h14V7H7v2z"/></svg>`, label: 'Jobs' },
      { id: 'worker-pools', icon: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M19.43 12.98c.04-.32.07-.64.07-.98s-.03-.66-.07-.98l2.11-1.65c.19-.15.24-.42.12-.64l-2-3.46c-.12-.22-.39-.3-.61-.22l-2.49 1c-.52-.4-1.08-.73-1.69-.98l-.38-2.65C14.46 2.18 14.25 2 14 2h-4c-.25 0-.46.18-.49.42l-.38 2.65c-.61-.25-1.17-.59-1.69-.98l-2.49-1c-.23-.09-.49 0-.61-.22l-2 3.46c-.13.22-.07.49.12.64l2.11 1.65c-.04.32-.07.65-.07.98s.03.66.07.98l-2.11 1.65c-.19.15-.24.42-.12-.64l2 3.46c.12.22.39.3.61-.22l2.49-1c.52.4 1.08.73 1.69.98l.38 2.65c.03.24.24.42.49.42h4c.25 0 .46-.18.49-.42l.38-2.65c.61-.25 1.17-.59 1.69-.98l2.49 1c.23.09.49 0 .61-.22l2-3.46c.12-.22.07-.49-.12-.64l-2.11-1.65zM12 15.5c-1.93 0-3.5-1.57-3.5-3.5s1.57-3.5 3.5-3.5 3.5 1.57 3.5 3.5-1.57 3.5-3.5 3.5z"/></svg>`, label: 'Worker pools' },
      { id: 'domain-mappings', icon: `<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24"><path d="M3 11h8V3H3v8zm2-6h4v4H5V5zm8-2v8h8V3h-8zm6 6h-4V5h4v4zM3 21h8v-8H3v8zm2-6h4v4H5v-4zm13-2h-8v8h8v-8zm-2 6h-4v-4h4v4z"/></svg>`, label: 'Domain mappings' },
    ];

    const sanitizedNavItems = rawNavItems.map(item => ({
      ...item,
      icon: this.sanitizer.bypassSecurityTrustHtml(item.icon)
    }));

    this.navItems.set(sanitizedNavItems);
  }
}
<nav class="shrink-0 h-full bg-white border-r border-gray-200 flex flex-col justify-between transition-all duration-200"
     [class.w-60]="!isCollapsed()"
     [class.w-16]="isCollapsed()">
  <div>
    <div class="h-12 flex items-center border-b border-gray-200" 
         [class.justify-between]="!isCollapsed()"
         [class.justify-center]="isCollapsed()"
         [class.px-4]="!isCollapsed()">
      <div class="flex items-center space-x-3">
         <svg class="w-7 h-7" data-icon-name="cloudRunSectionIcon" viewBox="0 0 32 32" fill="none" fill-rule="evenodd" aria-hidden="true"><path fill="var(--cm-sys-color-logo-grey-soft-tone, #757575)" d="M11.046 1l4.986 15H31z"></path><path fill="var(--cm-sys-color-logo-grey-deep-tone, #424242)" d="M31 16H16.032l-4.986 15zM2.31 31l4.994-2.503L11.046 16H6.05z"></path><path fill="var(--cm-sys-color-logo-grey-soft-tone, #757575)" d="M2.31 1l3.74 15h4.996L7.304 3.503z"></path></svg>
        @if (!isCollapsed()) {
          <span class="text-lg text-gray-700">Cloud Run</span>
        }
      </div>
      @if (!isCollapsed()) {
        <button class="p-1 text-gray-500 hover:bg-gray-100 rounded-full">
          <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 24 24"><path fill="currentColor" d="M16 12V4h1V2H7v2h1v8l-2 2v2h5.2v6h1.6v-6H18v-2l-2-2z"/></svg>
        </button>
      }
    </div>

    <ul class="py-2">
      @for(item of navItems(); track item.label) {
        @let isActive = activeView() === item.id;
        <li 
          class="cursor-pointer"
          [class.px-2]="!isCollapsed()"
          (click)="viewChange.emit(item.id)"
          [class.bg-blue-100]="isActive"
          [class.text-blue-700]="isActive"
          [class.font-medium]="isActive"
          [class.text-gray-600]="!isActive"
          [class.hover:bg-gray-100]="!isActive">
          <a href="#" (click)="$event.preventDefault()" class="flex items-center h-9 space-x-3" 
             [class.border-l-4]="isActive" 
             [class.border-blue-600]="isActive"
             [class.pl-3]="isActive && !isCollapsed()"
             [class.pl-4]="!isActive && !isCollapsed()"
             [class.justify-center]="isCollapsed()"
            >
            <div [innerHTML]="item.icon" class="w-5 h-5 shrink-0"></div>
            @if (!isCollapsed()) {
              <span>{{ item.label }}</span>
            }
          </a>
        </li>
      }
    </ul>
  </div>

  <div>
    <ul class="border-t border-gray-200 py-2">
      <li (click)="releaseNotesClicked.emit()" class="cursor-pointer">
        <a href="#" (click)="$event.preventDefault()" class="flex items-center h-10 space-x-3 text-gray-600 hover:bg-gray-100"
            [class.px-4]="!isCollapsed()"
            [class.justify-center]="isCollapsed()">
            <svg class="w-5 h-5 shrink-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"><path d="M17.5 4.5c-1.4 0-2.5-1.1-2.5-2.5S16.1 0 17.5 0S20 1.1 20 2.5s-1.1 2-2.5 2zm-12 7c-1.63 0-3.04.8-3.92 2.01A5.03 5.03 0 0 0 .5 17a5 5 0 0 0 5 5c1.76 0 3.26-.95 4.09-2.31l1.41 2.35l1.41-2.35C13.24 20.05 14.74 21 16.5 21c2.21 0 4-1.79 4-4s-1.79-4-4-4c-1.63 0-3.04.8-3.92 2.01a5.03 5.03 0 0 0-7.16 0A4.95 4.95 0 0 0 5.5 11.5z"/></svg>
            @if (!isCollapsed()) {
              <span>Release Notes</span>
            }
        </a>
      </li>
      <li (click)="toggleCollapse.emit()" class="flex items-center h-10 text-gray-600 hover:bg-gray-100 cursor-pointer"
          [class.px-4]="!isCollapsed()"
          [class.justify-center]="isCollapsed()">
        @if (!isCollapsed()) {
          <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7" /><path stroke-linecap="round" stroke-linejoin="round" d="M4 5v14" /></svg>
        } @else {
          <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7" /><path stroke-linecap="round" stroke-linejoin="round" d="M20 19V5" /></svg>
        }
      </li>
    </ul>
  </div>
</nav>
